products = [
    {
        '_id': '1',
        'name':'NVIDIA RTX 3080',
        'image':'/images/rtx3080.jpg',
        'description':'The GeForce RTX 3080 is an enthusiast-class graphics card by NVIDIA, launched on September 1st, 2020',
        'brand':'NVIDIA',
        'category':'GPU',
        'price':1499,
        'countInStock':10,
        'rating':5.0,
        'numReviews':4,
    },
    {
        '_id': '2',
        'name':'AMD Ryzen 9 3900XT',
        'image':'/images/ryzen9.jpg',
        'description':'Highest end AMD processor.',
        'brand':'AMD',
        'category':'CPU',
        'price':899,
        'countInStock':0,
        'rating':4.5,
        'numReviews':10,
    },
    {
        '_id': '3',
        'name':'Kingston Fury Beast 16GB',
        'image':'/images/kingstonfury.jpg',
        'description':'16GB DDR4 RAM',
        'brand':'Kingston',
        'category':'RAM',
        'price':75,
        'countInStock':20,
        'rating':4.0,
        'numReviews':15,
    },
    {
        '_id': '4',
        'name':'Samsung EVO Plus 970 1TB',
        'image':'/images/samsungevo.jpg',
        'description':'1TB SSD M.2 PCIe',
        'brand':'Samsung',
        'category':'SSD',
        'price':100,
        'countInStock':8,
        'rating':5.0,
        'numReviews':9,
    },
    {
        '_id': '5',
        'name':'MSI MAG B550 Tomahawk',
        'image':'/images/msitomahawk.jpg',
        'description':'MSI Motherboard',
        'brand':'MSI',
        'category':'Motherboard',
        'price':150,
        'countInStock':25,
        'rating':4.5,
        'numReviews':23,
    },
]
